### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by umida-boltaeva**

### CODE REVIEW

**Review by nickmcmillan — APPROVED** [review]
This all looks pretty good to me. Nice work on moving the sensitive credentials into a separate .env file  👍

Are the routes just placeholders for now?

**Comment by umida-boltaeva** [comment]
Thank you Nick.
Yes they are just placeholders for now.

**Comment by umida-boltaeva** [comment]
Hey Nick!
How are you doing? Hope you are well and safe.
I created a pull request yesterday. Can you just look through it when you
have some time, please?
Also, I am having a big hardship using firebase😣 I spent hours to fix it
yesterday night but just one small thing is not working. I connected the
user to the authentication but it's not showing up in the database.
Today I am going to learn firebase as thoroughly as I can. If I can't fix
the problem anyway, can we discuss it tomorrow on a video call?
Cheers.

**Comment by nickmcmillan** [comment]
Hi Umida!
Yeah I'm happy to have a call tomorrow to talk through it. I should warn you though that I'm no Firebase expert, but maybe just having someone to talk to about it might help (that's what I'm hoping!).

Where is the PR so I can take a look at what you've done so far?

**Comment by umida-boltaeva** [comment]
Hey Nick,

Good day! How are you?
I just want to ask you smth. Can we make the video call at 3 pm today
instead of 4 pm? Are you ok with that? And also one thing, I don't know how
to call via zoom. Can you please do it yourself?

**Pull request merged**
